/**
 * Solver-specific input/output types.
 *
 * The budget solver is deterministic code — no LLM involved. It takes structured
 * inputs describing the week's shape and produces a budget allocation that the
 * recipe engine fills.
 *
 * Source of truth: docs/product-specs/solver.md
 *
 * Relationship to core types:
 * - SolverInput is assembled by the orchestrator from user choices during planning.
 * - SolverOutput feeds into recipe generation (batch targets) and the weekly plan.
 */

import type { FlexSlot, Macros, MealEvent } from '../models/types.js';

/**
 * Everything the solver needs to allocate a weekly budget.
 * Assembled by the plan flow from the plan-proposer's output + user context.
 */
export interface SolverInput {
  weeklyTargets: Macros;
  events: MealEvent[];
  /** Flex slots consume from the fun food pool and replace meal-prep slots */
  flexSlots: FlexSlot[];
  mealPrepPreferences: {
    recipes: RecipeRequest[];
  };
  breakfast: {
    locked: boolean;
    recipeSlug?: string;
    caloriesPerDay: number;
    proteinPerDay: number;
  };
  /**
   * Plan 007: explicit 7 ISO dates covering the horizon. Required going forward.
   * Closes a latent bug where days covered only by events were missing from
   * dailyBreakdown (D32). During the strangler-fig window, the old code path
   * populates this from weekStart.
   */
  horizonDays?: string[];
  /**
   * Plan 007: pre-committed meal slots carried over from prior plan sessions.
   * The solver subtracts their calories/protein from the weekly budget before
   * distributing to new batches. Defaults to [] if undefined.
   */
  carriedOverSlots?: PreCommittedSlot[];
}

/**
 * A request for a specific batch of meal prep.
 * The solver assigns a uniform per-slot calorie target to all batches.
 * The recipe scaler then adjusts each recipe's ingredients to hit that target.
 */
export interface RecipeRequest {
  /** From database, or undefined for "generate new" */
  recipeSlug?: string;
  mealType: 'lunch' | 'dinner';
  /** ISO dates this batch covers */
  days: string[];
  /** In-horizon eating occasions only — overflow days are invisible to the solver (Plan 010) */
  servings: number;
  cuisineHint?: string;
}

/**
 * The solver's complete output — a budget allocation for the week.
 */
export interface SolverOutput {
  isValid: boolean;
  weeklyTotals: {
    calories: number;
    protein: number;
    /** Protected treat budget — config.targets.treatBudgetPercent of weekly calories */
    treatBudget: number;
    /** Sum of flex slot bonuses */
    flexSlotCalories: number;
  };
  dailyBreakdown: DailyBreakdown[];
  batchTargets: BatchTarget[];
  cookingSchedule: CookingScheduleDay[];
  warnings: string[];
}

export interface DailyBreakdown {
  /** ISO date */
  day: string;
  totalCalories: number;
  totalProtein: number;
  breakfast: Macros;
  lunch: { calories: number; protein: number; batchId?: string; flexBonus?: number };
  dinner: { calories: number; protein: number; batchId?: string; flexBonus?: number };
  flexSlots: FlexSlot[];
  events: MealEvent[];
}

/**
 * A batch target tells the recipe engine: produce N servings at these macros.
 * Calories and protein are hard constraints. Fat/carbs are for the recipe
 * generator to balance internally.
 */
export interface BatchTarget {
  id: string;
  recipeSlug?: string;
  mealType: 'lunch' | 'dinner';
  days: string[];
  servings: number;
  targetPerServing: Macros;
}

export interface CookingScheduleDay {
  /** ISO date */
  day: string;
  batchIds: string[];
}

// ─── Pre-committed slots (Plan 007: rolling horizon carry-over) ─────────────

/**
 * A materialized projection of a prior session's batch into the current horizon.
 *
 * Carries slug + day + mealType + frozen macros (copied from the source batch's
 * actualPerServing). Simplifies the solver's budget-subtraction math — it sees a
 * flat list of slots with known macros, not batches it would have to unpack.
 *
 * Intentionally a different type from Batch/ProposedBatch (D29 — load-bearing
 * separation for solver simplicity and cross-session ownership clarity).
 */
export interface PreCommittedSlot {
  day: string;
  mealTime: 'lunch' | 'dinner';
  recipeSlug: string;
  calories: number;
  protein: number;
  sourceBatchId: string;
}

// ─── Plan proposal types (plan-proposer sub-agent output) ─────────────────────

/**
 * A complete plan proposal generated by the plan-proposer sub-agent.
 * Contains recipe assignments, flex slot suggestions, and recipe gaps.
 * The solver runs on this to compute exact calorie targets.
 */
export interface PlanProposal {
  /** Recipe-to-slot assignments */
  batches: ProposedBatch[];
  /** Suggested flex meals */
  flexSlots: FlexSlot[];
  /** Recipes that need to be generated (not in DB) */
  recipesToGenerate: RecipeGap[];
  /** The solver output backing this proposal (attached after solver runs) */
  solverOutput?: SolverOutput;
}

/**
 * A proposed batch of meal prep in the plan proposal.
 * The plan-proposer picks recipes from the DB and assigns them to day ranges.
 */
export interface ProposedBatch {
  recipeSlug: string;
  recipeName: string;
  mealType: 'lunch' | 'dinner';
  /** ISO dates this batch covers (in-horizon only — the solver sees these) */
  days: string[];
  servings: number;
  /**
   * Days past the horizon end that this batch extends into (Plan 007 cross-horizon).
   * Used by the proposer to express cross-horizon extension intent.
   * NOT visible to the solver — only stored on the persisted Batch.eatingDays.
   * Defaults to [] so existing code constructing ProposedBatch without it keeps working.
   */
  overflowDays?: string[];
}

/**
 * A recipe gap — the plan-proposer determined the DB doesn't have enough
 * variety and suggests generating a new recipe.
 */
export interface RecipeGap {
  mealType: 'lunch' | 'dinner';
  /** ISO dates this batch would cover */
  days: string[];
  servings: number;
  /** What kind of recipe to generate — e.g., "Asian-inspired chicken stir-fry" */
  suggestion: string;
  /** Why this gap exists — e.g., "no Asian meals in past 2 weeks, need cuisine variety" */
  reason: string;
}
