/**
 * Solver-specific input/output types.
 *
 * The budget solver is deterministic code — no LLM involved. It takes structured
 * inputs describing the week's shape and produces a budget allocation that the
 * recipe engine fills.
 *
 * Source of truth: docs/product-specs/solver.md
 *
 * Relationship to core types:
 * - SolverInput is assembled by the orchestrator from user choices during planning.
 * - SolverOutput feeds into recipe generation (batch targets) and the weekly plan.
 */

import type { FunFoodItem, FlexSlot, Macros, MealEvent } from '../models/types.js';

/**
 * Everything the solver needs to allocate a weekly budget.
 * Assembled by the plan flow from the plan-proposer's output + user context.
 */
export interface SolverInput {
  weeklyTargets: Macros;
  events: MealEvent[];
  /** Flex slots consume from the fun food pool and replace meal-prep slots */
  flexSlots: FlexSlot[];
  mealPrepPreferences: {
    recipes: RecipeRequest[];
  };
  breakfast: {
    locked: boolean;
    recipeSlug?: string;
    caloriesPerDay: number;
    proteinPerDay: number;
  };
}

/**
 * A request for a specific batch of meal prep.
 * Includes the recipe's actual per-serving macros so the solver can compute
 * the weekly total from real data instead of uniform distribution.
 */
export interface RecipeRequest {
  /** From database, or undefined for "generate new" */
  recipeSlug?: string;
  mealType: 'lunch' | 'dinner';
  /** ISO dates this batch covers */
  days: string[];
  /** 2 or 3 servings per batch */
  servings: number;
  /** Actual per-serving macros from the recipe. If unknown, solver uses average. */
  actualMacros?: Macros;
  cuisineHint?: string;
}

/**
 * The solver's complete output — a budget allocation for the week.
 */
export interface SolverOutput {
  isValid: boolean;
  weeklyTotals: {
    calories: number;
    protein: number;
    /** Total fun food pool (20% of weekly target) */
    funFoodPool: number;
    /** Calories consumed by flex slot bonuses */
    flexSlotCalories: number;
    /** Remaining treat budget: funFoodPool - flexSlotCalories */
    treatBudget: number;
    /** funFoodPool as percentage of weekly calories */
    funFoodPercent: number;
  };
  dailyBreakdown: DailyBreakdown[];
  batchTargets: BatchTarget[];
  cookingSchedule: CookingScheduleDay[];
  warnings: string[];
}

export interface DailyBreakdown {
  /** ISO date */
  day: string;
  totalCalories: number;
  totalProtein: number;
  breakfast: Macros;
  lunch: { calories: number; protein: number; batchId?: string; flexBonus?: number };
  dinner: { calories: number; protein: number; batchId?: string; flexBonus?: number };
  flexSlots: FlexSlot[];
  events: MealEvent[];
}

/**
 * A batch target tells the recipe engine: produce N servings at these macros.
 * Calories and protein are hard constraints. Fat/carbs are for the recipe
 * generator to balance internally.
 */
export interface BatchTarget {
  id: string;
  recipeSlug?: string;
  mealType: 'lunch' | 'dinner';
  days: string[];
  servings: number;
  targetPerServing: Macros;
}

export interface CookingScheduleDay {
  /** ISO date */
  day: string;
  batchIds: string[];
}

// ─── Plan proposal types (plan-proposer sub-agent output) ─────────────────────

/**
 * A complete plan proposal generated by the plan-proposer sub-agent.
 * Contains recipe assignments, flex slot suggestions, and recipe gaps.
 * The solver runs on this to compute exact calorie targets.
 */
export interface PlanProposal {
  /** Recipe-to-slot assignments */
  batches: ProposedBatch[];
  /** Suggested flex meals */
  flexSlots: FlexSlot[];
  /** Recipes that need to be generated (not in DB) */
  recipesToGenerate: RecipeGap[];
  /** The solver output backing this proposal (attached after solver runs) */
  solverOutput?: SolverOutput;
}

/**
 * A proposed batch of meal prep in the plan proposal.
 * The plan-proposer picks recipes from the DB and assigns them to day ranges.
 */
export interface ProposedBatch {
  recipeSlug: string;
  recipeName: string;
  mealType: 'lunch' | 'dinner';
  /** ISO dates this batch covers */
  days: string[];
  servings: number;
}

/**
 * A recipe gap — the plan-proposer determined the DB doesn't have enough
 * variety and suggests generating a new recipe.
 */
export interface RecipeGap {
  mealType: 'lunch' | 'dinner';
  /** ISO dates this batch would cover */
  days: string[];
  servings: number;
  /** What kind of recipe to generate — e.g., "Asian-inspired chicken stir-fry" */
  suggestion: string;
  /** Why this gap exists — e.g., "no Asian meals in past 2 weeks, need cuisine variety" */
  reason: string;
}
